// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5VKpixdORQArLIW89awAmv9ZFp6ZYxsg',
    appId: '1:1088421932979:web:85b158484d0bb29ea7a5c6',
    messagingSenderId: '1088421932979',
    projectId: 'outflow-v2-9b250',
    authDomain: 'outflow-v2-9b250.firebaseapp.com',
    storageBucket: 'outflow-v2-9b250.appspot.com',
    measurementId: 'G-ZH4HLZGCJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkc1UZ-Is455kXIXgotsuLuGplkJ1XeXU',
    appId: '1:1088421932979:android:19808a9f9765b06fa7a5c6',
    messagingSenderId: '1088421932979',
    projectId: 'outflow-v2-9b250',
    storageBucket: 'outflow-v2-9b250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxVTxii8apSwb-tlXhhzOT6XHtyzylYk',
    appId: '1:1088421932979:ios:bbcc581e19489aa1a7a5c6',
    messagingSenderId: '1088421932979',
    projectId: 'outflow-v2-9b250',
    storageBucket: 'outflow-v2-9b250.appspot.com',
    iosClientId: '1088421932979-fscr4hbemgngjvg6c8f6jv2vrvpm86d9.apps.googleusercontent.com',
    iosBundleId: 'com.example.outflowV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxVTxii8apSwb-tlXhhzOT6XHtyzylYk',
    appId: '1:1088421932979:ios:7faadbdf265d77a8a7a5c6',
    messagingSenderId: '1088421932979',
    projectId: 'outflow-v2-9b250',
    storageBucket: 'outflow-v2-9b250.appspot.com',
    iosClientId: '1088421932979-f01e029jpa854rcigbfr0odkgo4227jd.apps.googleusercontent.com',
    iosBundleId: 'com.example.outflowV2.RunnerTests',
  );
}
